apiVersion: v1
description: Transaction-Requests-Service Helm chart for Kubernetes
name: transaction-requests-service
version: 7.4.1
appVersion: "7.4.1-snapshot"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/transaction-requests-service
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/documentation
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
