apiVersion: v1
description: Mojaloop Helm chart for Kubernetes
name: mojaloop
version: 8.1.0
appVersion: "ml-api-adapter: v8.1.0; central-ledger: v8.1.0; account-lookup-service: v7.4.0-snapshot; quoting-service: v7.4.0-snapshot; central-settlement: v7.4.0; central-event-processor: v7.1.1; bulk-api-adapter: v7.1.1-snapshot; email-notifier: v7.3.0; simulator: v8.1.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
