apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ml-api-adapter-handler-notification.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ml-api-adapter-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  default.json: {{ (tpl (.Files.Get "configs/default.json") . ) | quote }}
  {{- if .Values.sidecar.enabled }}
  default-sidecar.json: {{ (tpl (.Files.Get "configs/default-sidecar.json") . ) | quote }}
  {{- end }}
